apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-container
        # IMPORTANT: Use the public image you just pushed to Docker Hub
        image: techmagx/argocd-hello-world:510fb94
        ports:
        - containerPort: 80

