apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  # --- ADD THIS ANNOTATION BLOCK ---
  annotations:
    argocd.argoproj.io/health.lua: |
      hs = {}
      hs.status = "Healthy"
      hs.message = "Service is healthy, ignoring pending LoadBalancer IP"
      return hs
  # ---------------------------------
spec:
  type: LoadBalancer
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
